### ISSUE TITLE
Evaluate party_foul instead of rollbar as default exception tracker

### ISSUE THREAD

**Issue by mergulhao** [Helabs/pah#467] opened 2015-02-27 17:38 UTC
@maurogeorge What do you think?
https://github.com/dockyard/party_foul

//cc @eduardofiorezi

**Comment by maurogeorge** [comment] 2015-02-27 17:50
I like the rollbar :smile: what is the big win on change to party_foul?

I think it is a advantage with rollbar is that is tied with the heroku account of our customer, so when we deliver a project the customer can continue receive email if something wrong happens. The same way we have new relic for example.

What you think?

**Comment by TiuTalk** [comment] 2015-02-27 17:54
And **Rollbar** have a pretty good interface where you can search for exceptions, see all the occurrences and stuff you need to check the error.

**Comment by mergulhao** [comment] 2015-02-27 18:19
I think the advantages are:

 * One service less to sign in and take care (no account is required)
 * Track issues together with exceptions in Github Issues using a service that everyone in project already use daily

I see no advantage in rollbar that cannot be done with party_foul with less effort.

**Comment by thiagogabriel** [comment] 2015-02-27 18:28
`party_foul` is ok when we have a project we always take care. When we "finish" a project, the client still needs to know about any exception, and it is not reasonable to obbligate the client to use a private github for his. Rollbar is great on this case.
It is OK to move all internal projects to party_foul (if they aren't already), but the default case is to start a project fast to our clients.

**Comment by maurogeorge** [comment] 2015-02-27 18:33
We do not need a new account to use rollbar, it is tied to the heroku account.

We use the github as tracker for the internals projects, but customer projects we use the Pivotal Tracker, since this have points and integrates with the biscuit.

Again, I think it is a win for the rollbar this info be on the heroku of the customer. This way when the customer end your work with HE:labs he still receiving info about exceptions. With the party_foul they need a private GH repository and change some initializer. Not sure about that, but I think party_foul will start raise some exceptions, after we remove the customer repo from our GH if the initializer not be changed to a right repository.

**Comment by mergulhao** [comment] 2015-02-27 19:17
@TiuTalk I think Github Issues address the same goal.

@maurogeorge Yes, it is a new account. If it's an Heroku addon it's an account on an external app. It have an web interface and a lot of things that in my point of view is totally unnecessary and adds nothing to the goal of exceptions tracking.

@maurogeorge @thiagogabriel I don't think that the client wants to track exceptions... If it's moving to other vendor, It's a matter of who came after us to handle how to deal with it. In short: it's not our problem anymore. Let they address the way it thinks is better for him... How do you know the next one will like Rollbar to continue using it? Got it?

**Comment by thiagogabriel** [comment] 2015-02-27 20:43
@mergulhao `If it's moving to other vendor, It's a matter of who came after us to handle how to deal with it. In short: it's not our problem anymore.` And what if the project come backs to us and we don't know what is going on? It may be hard to reproduce some intermittent bug related to payment in production.

As far as I know, we can't setup party_foul automatically. We have to go to github.com, get the integration key and add to initializer/env var (production and staging) manually.

**Comment by mergulhao** [comment] 2015-02-27 22:21
@thiagogabriel How many times did it happened before?

@thiagogabriel I don't think that makes sense to decline to use a tool like this because it's config cannot be automated. If so, let's stop using rails... :smile:

**Comment by TiuTalk** [comment] 2015-02-28 01:59
Last time I used `party_foul` on a project was on **NFe** and, IMO, it was a complete mess.

My vote is :-1:

**Comment by lunks** [comment] 2015-02-28 12:29
Well, it looks like by the age of this gem that Rails config can be *fairly* automated. :trollface: 

My 2c: I like https://github.com/errbit/errbit a lot, easily configurable and you can have your own instance and the client can easily spin up their own instance if they want to and have a good-enough dev.

On the other hand, Rollbar is good too. My experience with both of these have been far better than `party_foul`. `party_foul` wasn't handling my errors and did not tell me anything.

**Comment by mergulhao** [comment] 2015-02-28 15:48
@TiuTalk How was the mess? It's working there at nfe. It shows environment of the exception (production, staging, etc), the exception itself, stacktrace, number of occurrences, url, controller, action, view, http headers... What more you need?

**Comment by mergulhao** [comment] 2015-02-28 15:50
@lunks The goal is to not use an external service here, because it's not needed. Use an external service I should keep it running is worst.

**Comment by lunks** [comment] 2015-03-01 13:35
It runs on Heroku and barely needs maintenance at all -- but it's your call. :watermelon:

**Comment by eduardofiorezi** [comment] 2015-03-04 20:58
I agree with @TiuTalk. The party_foul generate a lot of some issues, that was quite hard to read on NFE project. But ok for a small and initial project.

But a prefer rollback because it is easy to manage, it makes the deploys tracking and incorporates all the issues a simple way to view formatted for easy reading.

**Closed** 2016-05-18 14:51 UTC
Labels: voting for gem
